/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matkuldesktop;
    import matkuldesktop.user;
    import java.sql.*;
    import java.sql.SQLException;
    import javax.swing.JOptionPane;
    import java.awt.event.KeyEvent;
    import matkuldesktop.JframeRole;
    import matkuldesktop.Session;


/**
 *
 * @author Dzikr
 */


public class menuUtama extends javax.swing.JFrame {
    Connection con;
    Statement stm,stat;
    ResultSet rs;

    /**
     * Creates new form menuUtama
     */
    public menuUtama() {
        initComponents();
        koneksi(); // ini perlu ditambahkan supaya variabel con tidak null
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mRole = new javax.swing.JMenuItem();
        mUser = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Perpusatkaan");
        setMaximumSize(new java.awt.Dimension(1200, 800));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dzikr\\Downloads\\tes (1).jpg")); // NOI18N

        jMenuBar1.setToolTipText("");

        jMenu1.setText("File");

        jMenuItem1.setText("absen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("data karywan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data Master");

        mRole.setText("Role User");
        mRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRoleActionPerformed(evt);
            }
        });
        jMenu2.add(mRole);

        mUser.setText("Maintenence User");
        mUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUserActionPerformed(evt);
            }
        });
        jMenu2.add(mUser);

        laporan.setText("Laporan Absensi");
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        jMenu2.add(laporan);

        jMenuItem3.setText("Kelola karawan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 178, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUserActionPerformed
        // Cek admin dulu
    if (!"admin".equalsIgnoreCase(Session.currentRole)) {
        JOptionPane.showMessageDialog(
            this,
            "Hanya admin yang dapat membuka User Management",
            "Akses Ditolak",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }
    // Baru buka frame User
    user frameUser = new user();
    frameUser.setLocationRelativeTo(this);
    frameUser.setVisible(true);
    }//GEN-LAST:event_mUserActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (!"admin".equalsIgnoreCase(Session.currentRole)) {
        JOptionPane.showMessageDialog(
            this,
            "Hanya admin yang dapat membuka User Management",
            "Akses Ditolak",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }
        dataKaryawan role = new dataKaryawan();
        role.setLocationRelativeTo(null); // untuk posisi tengah
        role.setVisible(true);    
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRoleActionPerformed
        // Cek admin dulu
    if (!"admin".equalsIgnoreCase(Session.currentRole)) {
        JOptionPane.showMessageDialog(
            this,
            "Hanya admin yang dapat membuka Role Management",
            "Akses Ditolak",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }
    // Baru buka frame Role
    JframeRole frameRole = new JframeRole();
    frameRole.setLocationRelativeTo(this);
    frameRole.setVisible(true);

    }//GEN-LAST:event_mRoleActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         if (!"admin".equalsIgnoreCase(Session.currentRole)) {
        JOptionPane.showMessageDialog(
            this,
            "Hanya admin yang dapat membuka pengelolaan karyawan",
            "Akses Ditolak",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }
        // TODO add your handling code here:
        dataKaryawan role = new dataKaryawan();
        role.setLocationRelativeTo(null); // untuk posisi tengah
        role.setVisible(true);            // tampilkan frame-nya

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        absen3 role = new absen3();
        role.setLocationRelativeTo(null); // untuk posisi tengah
        role.setVisible(true);         
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        // TODO add your handling code here:
        laporan1 role = new laporan1();
        role.setLocationRelativeTo(null); // untuk posisi tengah
        role.setVisible(true);         
    }//GEN-LAST:event_laporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUtama().setVisible(true);
            }
        });
    }
    private void koneksi(){//begin
            try {
               Class.forName("com.mysql.jdbc.Driver");
               con=DriverManager.getConnection("jdbc:mysql://localhost/db_absensi", "root", "");
               stat=con.createStatement();
             } catch (ClassNotFoundException | SQLException e) {
               JOptionPane.showMessageDialog(null, e);
             }
      }//end begin
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem laporan;
    private javax.swing.JMenuItem mRole;
    private javax.swing.JMenuItem mUser;
    // End of variables declaration//GEN-END:variables
}
