/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matkuldesktop;
    import java.awt.event.KeyEvent;
    import static java.lang.System.err;
    import java.sql.Connection; 
    import java.sql.DriverManager; 
    import java.sql.Statement;
    import java.sql.ResultSet; 
    import java.sql.SQLException; 
    import javax.swing.JOptionPane; 
    import javax.swing.table.DefaultTableModel;
    import javax.swing.table.TableColumn;
    import java.sql.PreparedStatement;

/**
 *
 * @author Dzikr
 */
public class user extends javax.swing.JFrame {
    DefaultTableModel tabelmodel;
    Connection con=null;
    Statement stat;
    ResultSet res;
    PreparedStatement pst = null;
    String rool_id="";

    /**
     * Creates new form user
     */
    public user() {
        initComponents();
        koneksi();
        datatojtable();
        dataToComboBox();
        cekPass();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_user = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        cmd_keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_iduser = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_pass = new javax.swing.JTextField();
        txt_confirm = new javax.swing.JTextField();
        jComborole = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable_userKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_user);

        btn_simpan.setText("save");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_hapus.setText("Delete");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        cmd_keluar.setText("Exit");
        cmd_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_keluarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rak");

        txt_iduser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_iduserKeyPressed(evt);
            }
        });

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        txt_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_namaKeyPressed(evt);
            }
        });

        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
        });

        txt_confirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_confirmKeyPressed(evt);
            }
        });

        jLabel2.setText("Id User");

        jLabel3.setText("kode Kategory");

        jLabel4.setText("ConfirmPass");

        jLabel5.setText("Password");

        jLabel6.setText("Role Id");

        refresh.setText("Reload");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(btn_simpan)
                            .addGap(31, 31, 31)
                            .addComponent(btn_hapus)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refresh)
                            .addGap(50, 50, 50)
                            .addComponent(cmd_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txt_nama)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txt_pass)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txt_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(40, 40, 40))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComborole, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_iduser, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_iduser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComborole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_hapus)
                    .addComponent(cmd_keluar)
                    .addComponent(refresh))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmd_keluarActionPerformed

    private void txt_iduserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_iduserKeyPressed

        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER)
           { 
            cekdatauser();
          }  //end if
         
         
    }//GEN-LAST:event_txt_iduserKeyPressed

    private void txt_namaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namaKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER)
           { // begin
            txt_pass.requestFocus();   //panggil komponen yang akan di tuju
          }  //end if

    }//GEN-LAST:event_txt_namaKeyPressed

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER)
           { // begin
            txt_confirm.requestFocus();   //panggil komponen yang akan di tuju
          }  //end if

    }//GEN-LAST:event_txt_passKeyPressed

    private void txt_confirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_confirmKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER)
           { // begin
            jComborole.requestFocus();   //panggil komponen yang akan di tuju
          }  //end if
    }//GEN-LAST:event_txt_confirmKeyPressed

    private void jTable_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_userKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER)
           { // begin
              cekPass();
          }  //end if

    }//GEN-LAST:event_jTable_userKeyPressed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        String kodeuser=txt_iduser.getText();
        String namauser=txt_nama.getText();
        String pass=txt_pass.getText();
        String cpass=txt_confirm.getText();
        String roleid=jComborole.getSelectedItem().toString();
        String roolid;
                if (namauser.isEmpty() && kodeuser.isEmpty() && pass.isEmpty() && cpass.isEmpty() )
        {
             JOptionPane.showMessageDialog(null, "Ada kolom yang masih kosong");
             txt_iduser.requestFocus();
        }else
        {
            if (kodeuser.length()==8)
            {
               //Coding sini
               if (pass.equals(cpass))   
               {
                  cekrool_id();
               }else
               {
                   JOptionPane.showMessageDialog(null, "Password Belum Sama","Pesan",JOptionPane.ERROR_MESSAGE);
                   txt_confirm.requestFocus(); 
               }


            }else{
               JOptionPane.showMessageDialog(null, "Panjang Karakter Kurang dari 8 Digit");
               txt_iduser.requestFocus();
            }

            //ISI CODING CEK DIGIT 8 
        }//end if
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        if (txt_iduser.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Kode User Tidak Boleh Kosong");
            txt_iduser.requestFocus();
  
        }else
        {
           //PANGGIL METHOD HAPUS DATA
           hapus_data();
        }

    
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed

    }//GEN-LAST:event_refreshActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed
    public void hapus_data()
    {
        if(JOptionPane.showConfirmDialog(null, "Apakah Yakin Akan di Hapus ?","Informasi",JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION)
        {
            try{
                Statement SqlDel;
                SqlDel = con.createStatement();
                 SqlDel.executeUpdate("delete from tuser where idUser='"+  txt_iduser.getText()+"'");
                 
                JOptionPane.showMessageDialog(this,"Data berhasil Di Hapus","Success",JOptionPane.INFORMATION_MESSAGE);
                bersihkantextfiled();
                datatojtable();
 
            }catch(SQLException e){
                 JOptionPane.showMessageDialog(this,"Delete data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);       
              }

        } else
        {
           JOptionPane.showMessageDialog(null, "Kode User Batal Di Hapus");
           txt_iduser.requestFocus(); 
        }

    }//akhir Method
 
    public  void cekrool_id()
     {
         String roleid=jComborole.getSelectedItem().toString();
         
         try{
                     String sql="select *from trole where namarole='"+ roleid +"'";
                     ResultSet rsid=stat.executeQuery(sql);
                 if (rsid.next())
                     {
                         rool_id=rsid.getString("roleid");
                     }else
                     {
                         rool_id="0";
                     }
                      //Coding Insert Coding
                //memanggil method Insert Update
                 InserUpdate();

         }catch(SQLException err){
            JOptionPane.showMessageDialog(this, "Koneksi Gagal\n"+err.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
           }

     }//end method

      public void InserUpdate()
     {
        try{
          Statement strU=con.createStatement();
          Statement strI=con.createStatement();
          Statement str =con.createStatement();
                    
          String sqlu="select *from tuser where idUser='"+ txt_iduser.getText() +"'";
          ResultSet rsu=str.executeQuery(sqlu);
          
           java.util.Date tanggal=new java.util.Date();
           java.text.SimpleDateFormat setTanggal=new java.text.SimpleDateFormat("yyyy-MM-dd");
           String TglNow=setTanggal.format(tanggal);   
                 
          if (rsu.next())
          {
             String SqlU="update tuser set namauser='"+ txt_nama.getText() +"',password ='"+ txt_pass +"',roleid='"+ rool_id +"',datamodify='"+ TglNow +"' where idUser='"+ txt_iduser.getText() +"'";  
             strU.executeUpdate(SqlU);
             JOptionPane.showMessageDialog(null, "Data Sudah Di Ubah","Insert",JOptionPane.INFORMATION_MESSAGE);                   
             datatojtable();
             bersihkantextfiled();
 
          }else{
            String SqlI="insert into tuser values('"+ txt_iduser.getText() +"','"+ txt_nama.getText() +"','"+ txt_pass.getText() +"','"+ rool_id +"','"+TglNow+"','"+TglNow+"')";   
            strI.executeUpdate(SqlI);
            JOptionPane.showMessageDialog(null, "Data Sudah Di Simpan","Insert",JOptionPane.INFORMATION_MESSAGE);                   
            datatojtable();
            bersihkantextfiled();

          }
         
        }catch(SQLException err){
            JOptionPane.showMessageDialog(this, "Koneksi Gagal\n"+err.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
           }

     }//akhir Method

    private void koneksi(){//begin
            try {
               Class.forName("com.mysql.jdbc.Driver");
               con=DriverManager.getConnection("jdbc:mysql://localhost/db_absensi", "root", "");
               stat=con.createStatement();
             } catch (ClassNotFoundException | SQLException e) {
               JOptionPane.showMessageDialog(null, e);
             }
      }//end begin

    private void Aturkolom()
    {
        TableColumn column;
        jTable_user.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = jTable_user.getColumnModel().getColumn(0);
        column.setPreferredWidth(75);
        column = jTable_user.getColumnModel().getColumn(1);
        column.setPreferredWidth(200);
        column = jTable_user.getColumnModel().getColumn(2);
        column.setPreferredWidth(75);
        column = jTable_user.getColumnModel().getColumn(3);
        column.setPreferredWidth(75);
        column = jTable_user.getColumnModel().getColumn(4);
        column.setPreferredWidth(100);
        column = jTable_user.getColumnModel().getColumn(5);
        column.setPreferredWidth(100);
        column = jTable_user.getColumnModel().getColumn(6);
        column.setPreferredWidth(75);      
    }//method atur kolom
    
    private void datatojtable()
    {
        DefaultTableModel tb= new DefaultTableModel();
        // Memberi nama pada setiap kolom tabel
        tb.addColumn("Id User");
        tb.addColumn("Nama User");
        tb.addColumn("Password");
        tb.addColumn("Role Id");
        tb.addColumn("Nama Role");          
        tb.addColumn("Date Create");
        tb.addColumn("Date Modify");
        jTable_user.setModel(tb);
        try{
        // Mengambil data dari database
         res=stat.executeQuery("select a.iduser,a.namauser,a.password,a.roleid,b.namarole,a.datacreate,a.datamodify from tuser a,trole b where a.roleid=b.roleid");
        while (res.next())
        {
        // Mengambil data dari database berdasarkan nama kolom pada tabel
            // Lalu di tampilkan ke dalam JTable
            tb.addRow(new Object[]{
            res.getString("iduser"),
            res.getString("namauser"),
            res.getString("password"),
            res.getString("roleid"),
            res.getString("namarole"),
            res.getDate("datacreate"),
            res.getDate("datamodify")         
           });
          }
         //Aturkolom(); //pemanggilan class untuk mengatur kolom
        }catch (SQLException e){
        }       
        Aturkolom();
    }//end method
    
    private void dataToComboBox()
    {
        try{
            String sql = "SELECT * FROM trole";
            pst = con.prepareStatement(sql);
            res = pst.executeQuery();
            
               while (res.next()) {                
            
              jComborole.addItem(res.getString("namarole"));
            }
            
            res.last();
            int jumlahdata = res.getRow();
            res.first();
       
        }catch (SQLException e) {
        }        
    }//end method
    
     private void bersihkantextfiled()
    {
        txt_iduser.setText("");
        txt_nama.setText("");
        txt_pass.setText("");
        txt_confirm.setText("");
        txt_iduser.requestFocus();
    }
  private void cekdatauser()
    {
      try{
       
         
         if (txt_iduser.getText().length()!=8)
         {
               JOptionPane.showMessageDialog(null, "Panjang Karakter Kurang dari 8 Digit");
               txt_iduser.requestFocus(); 
         }else{
           String sqlcek="select *from tuser where idUser='"+ txt_iduser.getText() +"'";
           ResultSet rscek=stat.executeQuery(sqlcek);
            if (rscek.next())
               {   
                 txt_nama.setText(rscek.getString("namauser"));
                 txt_pass.setText(rscek.getString("password"));
                 txt_confirm.setText(rscek.getString("password"));
                  txt_nama.requestFocus(); 
              }else{
                  JOptionPane.showMessageDialog(null, "Id user Tidak Di temukan"); 
                  txt_nama.setText("");
                  txt_pass.setText("");
                  txt_confirm.setText("");
                  txt_nama.requestFocus();
             }
         }
      }catch(SQLException e)
        {
          JOptionPane.showMessageDialog(null,"GAGAL KETEMU");
        }     
    }//akhir Methor

    
     public void cekPass(){
          String Pass=txt_pass.getText();
          String Pass1=txt_confirm.getText(); 
           if (Pass.equals(Pass1))  //pengeceken karakter sama atau tidak pak Jtexfiled
           {
              jComborole.requestFocus();
           }else{
               JOptionPane.showMessageDialog(null, "Password Belum Sama","Pesan",JOptionPane.ERROR_MESSAGE);
               txt_confirm.requestFocus();
           }           
           
      }//akhir method


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton cmd_keluar;
    private javax.swing.JComboBox<String> jComborole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_user;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField txt_confirm;
    private javax.swing.JTextField txt_iduser;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_pass;
    // End of variables declaration//GEN-END:variables
}
